# Generated by Django 3.2.9 on 2021-12-07 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_auto_20211207_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='Users1',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('S', 'Sent')], max_length=10),
        ),
    ]
