# Generated by Django 3.2.9 on 2021-12-08 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0004_auto_20211207_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='Users1',
        ),
        migrations.AddField(
            model_name='my_profile',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
