# Generated by Django 3.2.9 on 2021-12-10 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_auto_20211208_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='status',
        ),
        migrations.AlterField(
            model_name='my_profile',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
