# Generated by Django 3.2.9 on 2021-12-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20211210_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('S', 'Sent')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
